### ISSUE TITLE
Can't run tests in IntelliJ

### ISSUE THREAD

**Issue by denisk20** [Trixt0r/spriter#28] opened 2015-11-22 07:53 UTC
I'm getting an error when trying to run any `main` method from any test (say, `BaseTest`):
`com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit`
I had to add this to pom.xml in order to make it work:

``` xml
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-platform</artifactId>
            <version>1.7.1</version>
            <classifier>natives-desktop</classifier>
            <scope>test</scope>
        </dependency>
```

(I have also changed all GDX versions to 1.7.1).

As a side note, when running `mvn clean test` from the root directory I get

```
SEVERE: null
java.nio.file.NoSuchFileException: assets/monster/basic_002.scml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at com.brashmonkey.spriter.tests.backend.LwjglTest.<init>(LwjglTest.java:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

Are you interested in converting the project to Gradle to make it more IDE-agnostic?

**Comment by Trixt0r** [comment] 2015-11-23 16:13
Yes, I wanted to switch to Gradle a while ago, but it wasn't as straight forward as I thought.

The problem is free time again.

**Comment by denisk20** [comment] 2015-11-26 19:45
No worries, we all have other jobs. I'll try to find time to submit a PR for that. One thing I need to know: are the tests in current project intended to be run from command line? Or is it OK to just make them executable from IDE? (I think the latter is the case but want to double check).

**Comment by Trixt0r** [comment] 2016-11-29 21:44
This seems to be an IDE and LibGDX issue, therefore closing...

Btw, I am currently migrating the project to gradle ;)

**Closed by Trixt0r** 2016-11-29 21:44 UTC
